version: '3.6'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
      # KEYCLOAK_LOGLEVEL: INFO
      # PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123 
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8081:8080
    networks:
      - keycloak

  keycloakdb:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres321
      KEYCLOAK_DB: keycloak
      KEYCLOAK_DB_USER: keycloak
      KEYCLOAK_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123 
    networks:
      - keycloak
  
  # api:
  #   build:
  #     context: .
  #     dockerfile: .deploy/api/Dockerfile
  #   image: xmlking/ngxapi:latest
  #   container_name: api
  #   environment:
  #     NODE_TLS_REJECT_UNAUTHORIZED: 0 
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres

  api:
    container_name: app
    build: .
    tty: true
    command: yarn start:dev
    ports:
      - '3001:3000'
      - '5555:5555'
    volumes:
      - .:/app
    depends_on:
      - keycloak_web
      - keycloakdb
    networks:
      - keycloak
    environment:
      # NODE_TLS_REJECT_UNAUTHORIZED: '0' 
      NODE_ENV: development
      KEYCLOAK_BASE_URL: http://keycloak_web:8080
    # env_file:
    #   - ./prisma/.env
  
  proxy:
    image: nginx
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./default-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - keycloak
    depends_on:
      - keycloak_web
      - api

volumes:
  postgres_data:

networks:
  keycloak:
    driver: bridge
